#!/usr/bin/env bash

FILE="/tmp/google.xml"
echo wget -q -U 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.6) Gecko/20070802 SeaMonkey/1.1.4' "translate.google.pl/#en|pl|$1" -O $FILE 

XML="xmlstarlet sel -t -v"
# find all 'Option' nodes under 'User' nodes where
# the Option.Name is 'Comments'
QUERY="//div[@id='gt-res-dict']"

RESULT=$($XML $QUERY $FILE 2>/dev/null)

echo "found '$RESULT'"
