#!/bin/bash
DATA_FILE="$HOME/data/wtimer/data.cvs"
SHEET="$HOME/data/wtimer/arkusz.ods"

if [ ! -f $DATA_FILE ]; then
    touch $DATA_FILE
fi

if [ "$1" = "" ]; then
    echo -n "Podaj przedmiot: ";
    read SUBJECT;
else
    SUBJECT="$0"
fi
if [ "$2" = "" ]; then
    echo -n "Podaj prefiks: ";
    read PREFIX;
else
    PREFIX="$0"
fi

echo -n "Podaj nr zadania: ";
read TASK_NO;

timing=(`timer_get_data_from_ods $SHEET $SUBJECT $PREFIX`)

keypress=''
res_time=${timing[0]} #RESERVE_TIME
i=${timing[1]} #TIME_PER_TASK

beep=0
TASK_TIME=0;

while [ 1 ]
do

    if [ -t 0 ]; then stty -echo -icanon time 0 min 0; fi

    clear
    min=$((i/60))
    sec=$((i-min*60))
    echo "$min:$sec";
    min=$((res_time/60))
    sec=$((res_time-min*60))
    echo "$min:$sec";

    if [ $i -le 0 ] && [ $res_time -le 0 ]; then
	echo -ne "\007"
    elif [ $i -le 0 ]; then
	if [ $beep == 0 ]; then
	    echo -ne "\007"
	fi
	beep=1
	res_time=$((res_time-1))
    else
	i=$((i-1))
    fi
    read keypress
    if [ "x$keypress" != "x" ]; then
	res_time=$((i+res_time));
	i=${timing[1]} #TIME_PER_TASK
	if [ $keypress != "u" ]; then
	    stat="d"
	else
	    stat="u"
	fi
	if [ -t 0 ]; then stty sane; fi
	echo "$SUBJECT;$PREFIX;$TASK_NO;$TASK_TIME;$stat" >> $DATA_FILE
	echo -n "Podaj nr zadania: "
	read TASK_NO;
	TASK_TIME=0
	if [ -t 0 ]; then stty -echo -icanon time 0 min 0; fi
	beep=0
    fi
    TASK_TIME=$((TASK_TIME+1))
    sleep 1;

done
