#!/bin/bash
TIME_PER_TASK=15
while [ 1 ]
do
    if [ -t 0 ]; then stty -echo -icanon time 0 min 0; fi

    keypress=''
    res_time=0
    i=$TIME_PER_TASK;
    beep=0
    while [ $i -gt 0 ] || [ $res_time -ge 0 ]
    do
	clear
	min=$((i/60))
	sec=$((i-min*60))
	echo "$min:$sec";
	min=$((res_time/60))
	sec=$((res_time-min*60))
	echo "$min:$sec";

	if [ $i -le 0 ]; then
	    if [ $beep == 0 ]; then
		echo -ne "\007"
	    fi
	    beep=1
	    res_time=$((res_time-1))
	else
	    i=$((i-1))
	fi
	read keypress
	if [ "x$keypress" != "x" ]; then
	    res_time=$((i+res_time));
	    i=$TIME_PER_TASK
	    beep=0
	fi
	sleep 1;
    done

    while [ "x$keypress" = "x" ]; do
	read keypress
	echo -ne "\007"
	sleep 0.5;
    done
    if [ -t 0 ]; then stty sane; fi

done
